const theme = {
  colors: {
    black: "#1B1723",
    blue: "#5D76DD",
    pink: "#FFA4F6",
    textPink: "#F46CE7",
    green: "#86EDDF",
    grey: "#7E8A8C",
    textGreen: "#39D8C3",
    mediumGrey: "#d7dbde",
    lightGrey: "#F1F2F7",
    lightBlue: "#E9EDFF",
    lightPink: "#FFE9FD",
    lightGreen: "#EAFFFC",
    purple: "#5D76DD",
    white: "#FFFFFF",
    whitePinkTint: "#FFF9FE",
  },
  typography: {
    largeTitleText: {
      fontSize: "50px",
      mobileFontSize: "40px",
      fontWeight: 700,
      lineHeight: "55px",
      mobileLineHeight: "45px",
    },
    largeBodyText: {
      fontSize: "30px",
      mobileFontSize: "20px",
      fontWeight: 300,
      lineHeight: "50px",
      mobileLineHeight: "30px",
    },
    headerLgText: {
      fontSize: "40px",
      mobileFontSize: "30px",
      fontWeight: 700,
      lineHeight: "50px",
    },
    headerMdText: {
      fontSize: "30px",
      mobileFontSize: "20px",
      fontStyle: "italic",
      fontWeight: 500,
      lineHeight: "40px",
    },
    headerSmText: {
      fontSize: "20px",
      mobileFontSize: "16px",
      fontWeight: 900,
      lineHeight: "24px",
    },
    normalBodyText: {
      fontSize: "20px",
      mobileFontSize: "16px",
      fontWeight: 100,
      lineHeight: "28px",
    },
    boldBodyText: {
      fontSize: "20px",
      mobileFontSize: "16px",
      fontWeight: 500,
      lineHeight: "24px",
    },
    linkText: {
      fontSize: "20px",
      mobileFontSize: "16px",
      fontStyle: "italic",
      fontWeight: 300,
    },
    navLinkText: {
      fontSize: "18px",
      mobileFontSize: "16px",
      fontWeight: 300,
    },
    largeBodyTextLineHeight: "30px",
  },
}

export default theme
